schema_version = "1.0.0"

id = "chibi_robo_dat_model"
version = "3.1.4"
name = "Chibi-Robo DAT Model"
tagline = "Import/export Chibi-Robo GameCube .dat models"
maintainer = "Made, StarsMmd, MikeyX"
type = "add-on"

license = [
  "SPDX:GPL-3.0-or-later",
]

blender_version_min = "4.5.0"

[permissions]
files = "Import/export scene data from/to disk"
